apiVersion: apps/v1
kind: Deployment
metadata:
  name: paiges-postproc-api
  labels:
    app: paiges-postproc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paiges-postproc-api
  template: 
    metadata:
      labels: 
        app: paiges-postproc-api
    spec:
      containers:
        - name: paiges-postproc-api
          image: paigesacr.azurecr.io/postproc/postproc:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4444
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 400m
          volumeMounts:
          - name: client-config-volume
            mountPath: /app/.env
            subPath: .env
          - name: uidata-volume
            mountPath: /afs
      volumes:
      - name: client-config-volume
        configMap:
          name: preproc-config
      - name: uidata-volume
        persistentVolumeClaim:
          claimName: my-azurefile                
      nodeSelector:
        agentpool: appsnodepool                 
--- 
# Service
apiVersion: v1
kind: Service
metadata:
  name: paiges-postproc-api-loadbalancer-service
  labels:
    app: paiges-postproc-api
spec:
  type: ClusterIP #NodePort
  selector:
    app: paiges-postproc-api
  ports:
    - name: http
      port: 80
      targetPort: 9100
