apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
data:
  .env: |
    #env import
    #env configured
    #tapp_listen_change_streams=true
    tapp_result_size=50
    tapp_confidence_threshold=90
    downloadAllThreshold=500
    tapp_auto_processing=true
    tapp_auto_extraction=false
    tapp_preprocessor_api_host=http://106.51.73.100:8902
    tapp_extraction_api_host=http://106.51.73.100:9201
    tapp_storage_provider=localblob
    tapp_storage_access_key=tapp2data
    tapp_storage_access_secret=C38zpM1CfufDmqcelnI/VvjIUpB6Fyoj8QUtsKrFs4f7pAKCpzMFRClSOhJW1thKSOdZB7Jm3OWughlSKEsuxg==
    tapp_storage_container=import
    tapp_storage_asset_container=assets
    tapp_storage_sampleInvoices_container=sampleinvoices
    tapp_storage_region=
    initialDocsExtracted=0

    #mongodb database name and host
    tapp_mongodb_host=mongodb://mongodb-test.default.svc.cluster.local/test
    tapp_mongodb_db_name=docker_db
    tapp_api_host=http://106.51.73.100:8085

    #mysql database settings
    sql_db_host=paigessql.postgres.database.azure.com
    sql_db_name=paiges
    sql_db_port=5432
    sql_db_username=paiges_sql@paigessql
    sql_db_password="qW6jL2yF3xC7dI2"

    #consumption_db settings
    consumption_sql_db_host=paigessql.postgres.database.azure.com
    consumption_sql_db_name=paiges
    consumption_sql_db_port=5432
    consumption_sql_db_username=paiges_sql@paigessql
    consumption_sql_db_password="qW6jL2yF3xC7dI2"
    consumption_sql_db_table=paiges_usage
    consumption_subscription_id=76bcd967-9969-4ebd-b2c5-3d91f9c7cac7

    #reports-service
    reportsDataPath=http://106.51.73.100:8903/collect_metadata

    #postgreSQL tableNames
    metaDataTable=blinkit_test_document_metadata
    resultDataTable=blinkit_test_document_result
    rpaMetaDataTable=blinkit_test_rpa_metadata

    #storeDataInPostgreSQL
    storeDataInPostgreSQL=1

    #rpa starts here
    rpa_integration_mode=cloud
    rpa_authentication_domain= https://account.uipath.com/
    rpa_orchestrator_domain=https://platform.uipath.com/
    rpa_job_ids=

    #RPA Cloud integration configuration keys
    rpa_account_logical_name=taosmyhlxp
    rpa_tenant_logical_name=TAODefaulta1n6222679
    rpa_tenant_organization_id=100469
    rpa_refresh_token=lkVBXp5KOVt-AbUfEDqUFRCdo0DfgAwdnLDWMqIm057Bl
    rpa_client_id=8DEv1AMNXczW3y4U15LL3jYf62jK93n5

    #RPA On-Premise integration configuration keys
    rpa_tenant_name=
    rpa_user_name=
    rpa_password=
    tapp_review_submit_url=


    #Network paths - Root location
    tapp_localBlobStorage=/usr/src/UI_data/app

    #static files url
    tapp_images_static_url=/static

    #download results
    tapp_download_results_api=http://106.51.73.100:8902/download/results
    downloadResultPath=/downloads/
    download_originalFile_api=http://106.51.73.100:8902/download/pdf
    download_ListViewFiles_api=http://106.51.73.100:8903/ui_downloads/list_view
    tapp_invoice_tiff_url=http://127.0.0.1:8081
    query_add_workflow_API_URL=http://180.151.86.53:90/api/TAPP/SaveTappData
    query_delete_workflow_API_URL=http://180.151.86.53:90/api/DeleteTAPP/DeleteQueryData

    #mongo atlas
    #databaseUrl=mongodb+srv://kanak:kanak_optimal@cluster0.shybo.mongodb.net/paiges_kgs?retryWrites=true&w=majority&useNewUrlParser=true&useUnifiedTopology=true
    mongo_Atlas_Host_Url=mongodb+srv://pAIges_DB:r1JliLnVh37DzRux@cluster0.fbbiy.mongodb.net/demo_db?retryWrites=true&w=majority&useNewUrlParser=true&useUnifiedTopology=true

    #others
    clientAddress=http://106.51.73.100:8085
    emailServiceProvider=gmail
    senderEmailId=yourgamil@gmail.com
    senderPassword=password

    #for send email
    emailEndPoint=https://paigessendemail.centralindia-1.eventgrid.azure.net/api/events
    mailSendKey=iVEOjpKIERR9gvo4psYRGpOMD3wRbEucerYHGdYxbSU=

    #encryption/decryption
    encryptionKey=PAIGESISPOWEREDBYTAOAUTOMATION2022
    decryptionTokenId=vtucupWt0pZBVYcPVgzQ/A==

    #extraction-assist
    formatIdentifierRootPath=http://106.51.73.100:8903/format_identifier/
    pathFinderRootPath=http://106.51.73.100:8903/path_finder/
    pathFinderCorrectionsPath=http://106.51.73.100:8903/corrections/
    RAISE_TICKET_EMAIL=amit.rajan@taoautomation.com

    #common
    ALERT_TIMEOUT=5000
    AUTO_REFRESH_IN=5000
    HOW_IT_WORKS_URL=https://www.taoautomation.com/what-we-do/productized-solutions/tao-paiges/
    maximumAllowedPages=50
    maximumFileSizeLimit=5
    adminEmailId=pAIges.admin@taoautomation.com
    DEFAULT_EA_TIMEGAP=90

    #reviewer
    ACTIVITY_TIME_REVIEWER=300
    ALERT_DISSMISS_REVIEWER=60
    AUTO_UNLOCK_DOCUMENT_IN=30

    #client-specific
    SIGNUP_PAGE_VISIBILITY=0
    DASHBOARD_VISIBILITY=1
    PROCESSING_VISIBILITY=1
    SETTINGS_VISIBILITY=1
    ACTIONS_VISIBILITY=1
    POINT_AND_SHOOT_VISIBILITY=1
    EXTRACTION_ASSIST_VISIBILITY=1
    EXTERNAL_LOGS_VISIBILITY=0
    DETAILED_LOGS=1
    LOGS_LENGTH=2000
    DAILY_CONSUMPTION_LIMIT_VISIBILITY=1
    FAQ_PAGE_VISIBILITY=0
    CARDVIEW_VISIBILITY=0
    VIEWER_ROLE_VISIBILITY=0
    TIPS_VISIBILITY=0
    LINE_ITEMS_VISIBILITY=1
    ADMIN_UPLOAD_VISIBILITY=1
    TAPP_CHANGES_VISIBILITY=1
    LOGO_VISIBILITY=1
    UPLOAD_BUTTON_VISIBILITY=0
    STP_AND_ACE_VISIBILITY=0
    REASSIGN_BUTTON_VISIBILITY=1

    #LIMITS
    CONSUMPTION_LIMIT=36300

    #either set CONSUMPTION_UNIT to "documents" or "pages" only.
    CONSUMPTION_UNIT=documents
    COMPARING_VALUES_IN_METADATA=["postingStatus","statusMsg","approverEmail","approvalStatus","approverComment"]

    #for swiggy it should be 0 and for KGS it should be 1
    DOCTYPES_VISIBILITY=1
    DOCUMENT_TYPES_LIST=[{ "name": "Discrepancy Note", "checked": "true" },{ "name": "Invoice", "checked": "true" }]
    DOCTYPE_CHECK_FOR_ROLES=["clientadmin", "reviewer", "approver"]

    #Admin Role Limitation
    ALL_ROLES_VISIBILITY_FOR_ADMIN=1

    #default functionality on review page - value can be either 'pointAndShoot' or 'zoom'
    DEFAULT_FUNCTIONALITY=pointAndShoot

    #session
    SESSION_EXPIRE_TIME=2
    SESSION_EXPIRE_TIME_UNIT=hours

    #mergeTometadata
    tapp_merge_result_metadata=invoiceNumber,invoiceDate,totalAmount,vendorName

    #business Rule Validation
    businessRuleValidation_APIRootPath=http://106.51.73.100:8903/
    callbackUrlForValidationAPI=http://106.51.73.100:8085
    BUZ_RULE_API_VISIBILITY=1

    #VAPT
    INVALID_FORM_TAGS=["<script", "/script", "script>", "<title", "/title", "title>", "<import", "/import", "import>", "<link", "/link", "link>"]

    #upload related
    tapp_orgtype_options=[{"orgTypeId":"ORG_001", "orgType":"Swiggy"}]
    tapp_doctype_options=[{"docTypeId":"DOC_001", "docType":"Discrepancy Note"},{"docTypeId":"DOC_002", "docType":"Invoice"}]

    #Sub folders - list all sub folders in the above directory. Also include preprocessor directory in this list.
    tapp_localFileTypesAllowed={"pdf":"application/pdf","tiff":"image/tiff"}
    tapp_localSubFolders_allowed={"import":"/import/","assets":"/assets/","sampleinvoices":"/sampleinvoices/","preprocessor":"/preprocessor/","downloads":"/downloads/"}

    #dashboard
    organizationConfig={"orgName":"KGS", "orgID":"19012", "expiry":"June 10 2022", "pageQuota":10}
    chartsAPIRootPath=http://106.51.73.100:8903/
    postingTabInDashboard=0
    dashboardOptions=[{ "name": "Configure", "visibility": 0 },{ "name": "Other Graphs", "visibility": 0 }]
    dashboardCalenderPrevMonthValue=0

    #black-listed domains
    BLACKLISTED_DOMAINS=["gmail","outlook", "prontonmail", "aol", "zoho", "iCloud", "yahoo", "gmx"]

    #not-extracted fields list
    unExtractedfields=["invoiceNumber", "poNumber", "invoiceDate", "totalAmount", "subTotal", "SGSTAmount", "CGSTAmount", "vendorAddress", "vendorGSTIN", "vendorName", "vendorEmail", "totalGSTAmount"]

    #delete-reasons
    deleteReasonOptions=[{ "id": "1", "name": "Not an Invoice" }, { "id": "2", "name": "Mandatory field Missing" }, { "id": "3", "name": "Invoice Page Missing" }, { "id": "4", "name": "VendorMasterData Incorrect/Missing" }, { "id": "5", "name": "Multiple Invoices in file" }, { "id": "6", "name": "Invoice Calculation Incorrect" }, { "id": "7", "name": "Invalid GST Rate" }, { "id": "8", "name": "Invoice Not Legible" }, { "id": "9", "name": "Others" }]

    #reassign-reasons
    reassignReasonOptions=[{"id": "1", "name": "Handwritten Invoice" },  { "id": "2", "name": "GST summary table not available" }, { "id": "3", "name": "Manual Calculation Needed" }, {"id": "4", "name": "CGST & SGST Amount Combined" }, {"id": "5", "name": "Tax Slab Not Defined" }, {"id": "5", "name": "Others" }]

    #purge document
    KeysToBeDeletedFromDocColl={"invoiceNumber":1,"totalAmount":1,"vendorId":1,"invoiceDate":1,"currency":1, "bar_qr_data":1 }
    KeysToBeDeletedFromResultColl={"documentInfo":1, "documentLineItems":1, "vendorId":1 }

    #statusChangeEventConfig for Microsoft Eventgrid 
    statusChangeEventConfig={"rootPath": "","aegSasKey":"","topic": "","subject": "","eventType": "","eventTrigger": 1}

    #client-specific project configs 
    #for bcp clientLogo must be 'bcp-logo.PNG' and clientLogoStyle must be 'logo-style-bcp' 
    #for swiggy clientLogo must be 'swiggy-logo.png' and clientLogoStyle must be 'logo-style-swiggy'
    projectConfigurations={"projectName":"TAPP","logoName":"tappLogoHeader.svg","appVersion": "1.0.0","clientLogo":"pierian-Logo.png","clientLogoStyle":"logo-style-bcp"}

    #dashboard Filters

    dashboardFilters={"extraction": [{ "name": "sla_flag", "type": "radio", "visibility": 0 },{ "name": "documentType", "type": "checkBox", "visibility": 1 },{ "name": "vendor name", "type": "searchAndSelect", "visibility": 1 },{ "name": "billing state", "type": "searchAndSelect1", "visibility": 0 }],"posting": [{ "name": "posting status", "type": "radio", "visibility": 1 },{ "name": "documentType", "type": "checkBox", "visibility": 1 },{ "name": "vendor name", "type": "searchAndSelect", "visibility": 1 }]}
