apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-deployment-1
  namespace: default
spec:
  serviceName: kafka1
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker-1
  template:
    metadata:
      labels:
        app: kafka-broker-1
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "20.204.212.156"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_CREATE_TOPICS
          value: "test-topic:3:2:compact"
        - name: KAFKA_LOG_DIRS
          value: /kafka/kafka-logs
        - name: KAFKA_BROKER_ID
          value: "0"  # Updated the broker ID to 0, assuming it's the first broker
        - name: KAFKA_JMX_PORT
          value: "5555"
        - name: KAFKA_CLEANUP_POLICY
          value: "compact"
      nodeSelector:
        agentpool: kafkapool
---
apiVersion: v1
kind: Service
metadata:
  name: kafka1
  namespace: default
  labels:
    app: kafka-broker-1
spec:
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka-broker-1
  type: LoadBalancer

